# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a919bc0ac41bed9409bb066832246a1651646bcbd65935b2585aa17c179a8e910bcd303fbfa6d46bf6119698d683d8444192b5ef710ac0d2b04d0fac81b7d237

test:
  secret_key_base: aaaa479859fb98f57691d3d0d7cc99e315938debf67edca8f7607c6b97b6a2d872b99df3941528946c572b05715223bda63959fdb523cbee89897a94438234c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
